### ISSUE TITLE
Format phone number

### ISSUE THREAD

**Issue by talhaizzettin** [joelkanyi/kompose-country-code-picker#62]
How I can get Formatted phone number to show it in my app the format it change by country

**Comment by joelkanyi** [comment]
https://joelkanyi.github.io/kompose-country-code-picker/customizations/
![Screenshot_2024-07-04-20-58-10-680_com android chrome](https://github.com/joelkanyi/kompose-country-code-picker/assets/50293753/800c2291-fe93-4fc8-ba4f-be4fe683c6c9)

**Comment by talhaizzettin** [comment]
I mean, for example, when I write a Turkish number, it is written this way: +90 555 555 55 55. I want it in this format. Every country has its own format. This functions erases these spaces

**Comment by joelkanyi** [comment]
Hey @talhaizzettin I had not implemented this, I'll add it

**Comment by joelkanyi** [comment]
Hey @talhaizzettin update the lib to version 1.2.3 then you'll be able to use this:

`state.getFullyFormattedPhoneNumber()`
