### ISSUE TITLE
Set phone number

### ISSUE THREAD

**Issue by talhaizzettin** [joelkanyi/kompose-country-code-picker#65]
if I get number when user signup the user go to settings screen to edit phone number i show set the number in KomposeCountryCodePicker how can i change country code and show number next to country code ? 

i cant save the country code in my app because the user number come form backend like this +905555555555 user can signup from web or ios, before use compose UI in xml i used library do it now i cant find library  in compose UI your library is the best but need some fixes .

also can u add textStyle to use our text style in the TextField

Thank you

**Comment by joelkanyi** [comment]
Hey @talhaizzettin 

I will implement a feature this week that will automatically preselect the country code and format the phone number accordingly in the text field when someone enters a phone number with the country code.

Regarding the styling of text in the TextField, I apologize for the oversight. I will include both fixes in the next release.
