### ISSUE TITLE
Unable to disable interaction

### ISSUE THREAD

**Issue by Sir-Dave** [joelkanyi/kompose-country-code-picker#89]
Hello there! So I have a use case where I would like to disable touch interaction based on a boolean flag, similar to the "enabled" attribute in composables. However, I noticed that this library does not allow me to do that no matter what I have tried.

**Comment by joelkanyi** [comment]
Hey @Sir-Dave I will add that

**Comment by joelkanyi** [comment]
Hey @Sir-Dave a new paramater called `enabled` has been added, update the library to `1.2.7`
