### ISSUE TITLE
Localization to "Select Country" and "Search" place holder in this screen

### ISSUE THREAD

**Issue by ahmetnova** [joelkanyi/kompose-country-code-picker#98]
How can I add localization to "Select Country" and "Search" place holder in this screen? is there any way to do that? 
![Screenshot_20241218_101448_OneGB](https://github.com/user-attachments/assets/cbc7d84a-59ab-4c8a-a29d-7103fc30a567)

**Comment by adityaraute** [comment]
Can you describe what you mean by 'adding localisation'?

**Comment by ahmetnova** [comment]
localization is adapting the text to suit a specific language

**Comment by ahmetnova** [comment]
I just want to change the strings in this screen, is that possible? @adityaraute

**Comment by adityaraute** [comment]
Would be better to ask @joelkanyi

**Comment by joelkanyi** [comment]
Hey @ahmetnova one thing before I answer you, are the countries in the list adapting to your localization?

**Comment by ahmetnova** [comment]
countries in the list is addapting the localization.
only the header "Select Country" and search placeHolder "Search" aren't addapting. thanks in advanced @joelkanyi

**Comment by joelkanyi** [comment]
Okay great thanks, let me localize them and publish a new version

**Comment by joelkanyi** [comment]
Kindly update to version 1.2.9
